-- Course Registration System: database schema (Oracle 12c+ / XE 21c / 23ai Free)
-- Run as user CRS:  sqlplus crs/crs@localhost:1521/XEPDB1 @database/schema.sql
-- (or open it in SQL Developer connected as CRS and press F5 "Run Script")
-- Sample data matches com.crs.fake.FakeDataStore, so the app behaves the same with fakes and with Oracle.
--
-- Oracle notes:
--   * No ENUM type: VARCHAR2 + CHECK constraint instead.
--   * No TIME type: class times are stored as 'HH24:MI' text, e.g. '09:30' (Java: LocalTime.parse).
--   * Auto numbers: GENERATED BY DEFAULT AS IDENTITY.
--   * Run-again friendly: each DROP ignores "table does not exist" (ORA-00942).

BEGIN EXECUTE IMMEDIATE 'DROP TABLE waitlist CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE registrations CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE completed_courses CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE prerequisites CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE courses CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE admins CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE students CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

CREATE TABLE students (
    student_id  VARCHAR2(10)  PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    email       VARCHAR2(100) NOT NULL UNIQUE,
    password    VARCHAR2(100) NOT NULL,
    cgpa        NUMBER(4,2)   NOT NULL CHECK (cgpa BETWEEN 0 AND 10)
);

CREATE TABLE admins (
    admin_id    VARCHAR2(10)  PRIMARY KEY,
    name        VARCHAR2(100) NOT NULL,
    email       VARCHAR2(100) NOT NULL UNIQUE,
    password    VARCHAR2(100) NOT NULL
);

CREATE TABLE courses (
    course_code  VARCHAR2(10)  PRIMARY KEY,
    title        VARCHAR2(100) NOT NULL,
    credits      NUMBER(2)     NOT NULL CHECK (credits >= 0),
    capacity     NUMBER(4)     NOT NULL CHECK (capacity > 0),
    seats_left   NUMBER(4)     NOT NULL CHECK (seats_left >= 0),
    waitlist_cap NUMBER(4)     DEFAULT 10 NOT NULL,
    class_day    VARCHAR2(9)   CHECK (class_day IN ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    start_time   VARCHAR2(5),  -- 'HH24:MI'
    end_time     VARCHAR2(5)   -- 'HH24:MI'
);

CREATE TABLE prerequisites (
    course_code  VARCHAR2(10) NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
    prereq_code  VARCHAR2(10) NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
    PRIMARY KEY (course_code, prereq_code)
);

CREATE TABLE completed_courses (
    student_id   VARCHAR2(10) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
    course_code  VARCHAR2(10) NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
    PRIMARY KEY (student_id, course_code)
);

CREATE TABLE registrations (
    reg_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   VARCHAR2(10) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
    course_code  VARCHAR2(10) NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
    status       VARCHAR2(10) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','CANCELLED')),
    reg_time     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE waitlist (
    waitlist_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   VARCHAR2(10) NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,
    course_code  VARCHAR2(10) NOT NULL REFERENCES courses(course_code) ON DELETE CASCADE,
    joined_time  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_waitlist UNIQUE (student_id, course_code)
);

-- ---------------- Sample data ----------------
INSERT INTO students VALUES ('S001','Arun Kumar','arun@college.edu','pass',8.50);
INSERT INTO students VALUES ('S002','Priya Sharma','priya@college.edu','pass',9.20);
INSERT INTO students VALUES ('S003','Rahul Das','rahul@college.edu','pass',7.80);

INSERT INTO admins VALUES ('A001','Admin','admin@college.edu','admin');

INSERT INTO courses VALUES ('CS101','Programming in Java',4,3,3,10,'MONDAY','09:00','10:00');
INSERT INTO courses VALUES ('CS102','Data Structures',    4,3,3,10,'MONDAY','09:30','10:30');
INSERT INTO courses VALUES ('CS201','Advanced Java',      3,3,3,10,'TUESDAY','11:00','12:00');
INSERT INTO courses VALUES ('CS202','Database Systems',   3,1,1,10,'WEDNESDAY','14:00','15:00');
INSERT INTO courses VALUES ('CS301','Machine Learning',   3,2,2,10,'THURSDAY','10:00','11:00');

INSERT INTO prerequisites VALUES ('CS201','CS101');
INSERT INTO prerequisites VALUES ('CS301','CS102');
INSERT INTO prerequisites VALUES ('CS301','CS201');

INSERT INTO completed_courses VALUES ('S002','CS101');

COMMIT;
